name: Deploy Theme

on:
  push:
    branches: [ "staging", "prod" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Build Theme
        run: |
          npm install
          npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github_deploy_ed25519
          chmod 600 ~/.ssh/github_deploy_ed25519

      - name: Rsync Theme to Server
        run: |
          rsync -az --delete \
            -e "ssh -p 9073 -i ~/.ssh/github_deploy_ed25519 -o StrictHostKeyChecking=accept-new" \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            --exclude "src" \
            --exclude ".env" \
            --exclude ".DS_Store" \
            ./ \
            alwerastaging@ld12.einfachtoll.com:/var/www/alwerastaging/alwerastaging/staging.alwera.at/wp-content/themes/alwera/
